import { Trade, TradeType, TradeStatus, Outcome } from './types';

// Demo trades for the landing page dashboard preview
export const MOCK_TRADES: Trade[] = [
  {
    id: '1',
    pair: 'BTC/USDT',
    type: TradeType.LONG,
    entryPrice: 42000,
    exitPrice: 43500,
    size: 10000,
    leverage: 10,
    pnl: 3571,
    pnlPercentage: 35.7,
    date: '2023-10-25T10:00:00Z',
    status: TradeStatus.CLOSED,
    outcome: Outcome.WIN,
    notes: 'Clean breakout retest.',
    setup: 'Trend Continuation',
    mistakes: []
  },
  {
    id: '2',
    pair: 'ETH/USDT',
    type: TradeType.SHORT,
    entryPrice: 2200,
    exitPrice: 2250,
    size: 5000,
    leverage: 5,
    pnl: -113,
    pnlPercentage: -2.2,
    date: '2023-10-26T14:30:00Z',
    status: TradeStatus.CLOSED,
    outcome: Outcome.LOSS,
    notes: 'Stop hunt, entered too early.',
    setup: 'Reversal',
    mistakes: ['Early Entry']
  },
  {
    id: '3',
    pair: 'SOL/USDT',
    type: TradeType.LONG,
    entryPrice: 95,
    exitPrice: 105,
    size: 2000,
    leverage: 3,
    pnl: 631,
    pnlPercentage: 31.5,
    date: '2023-10-27T09:00:00Z',
    status: TradeStatus.CLOSED,
    outcome: Outcome.WIN,
    notes: 'Strong momentum on 4H.',
    setup: 'Breakout',
    mistakes: []
  },
  {
    id: '4',
    pair: 'BTC/USDT',
    type: TradeType.SHORT,
    entryPrice: 44000,
    exitPrice: 44200,
    size: 15000,
    leverage: 20,
    pnl: -681,
    pnlPercentage: -4.5,
    date: '2023-10-28T11:15:00Z',
    status: TradeStatus.CLOSED,
    outcome: Outcome.LOSS,
    notes: 'Revenge trade after missing the pump.',
    setup: 'Impulse',
    mistakes: ['Revenge Trading', 'Over-leverage']
  },
  {
    id: '5',
    pair: 'LINK/USDT',
    type: TradeType.LONG,
    entryPrice: 14.5,
    exitPrice: 16.2,
    size: 3000,
    leverage: 5,
    pnl: 1758,
    pnlPercentage: 58.6,
    date: '2023-10-29T16:45:00Z',
    status: TradeStatus.CLOSED,
    outcome: Outcome.WIN,
    notes: 'Perfect S/R flip.',
    setup: 'S/R Flip',
    mistakes: []
  }
];
